= Http Builder NG Users Guide
David Clark & Christopher J. Stehno
v0.9.14, September 2016
:toc: left
:toclevels: 3

== Introduction

WARNING: This document is a work-in-progress, and currently has a lot of gaps. We are working to fill in the holes, but feel free to suggest content by creating an issue.

Http Builder NG is a modern Groovy DSL for making http requests. It requires Java 8 and a modern Groovy. It is built against Groovy 2.4.x,
but it doesn't make any assumptions about which version of Groovy you are using. The main goal of Http Builder NG is to allow you to make
http requests in a natural and readable way.

The project web site is: https://github.com/dwclark/http-builder-ng

Issue tracking is handled via GitHub: https://github.com/dwclark/http-builder-ng/issues

== History

Http Builder NG was forked from the HTTPBuilder project originally developed by Thomas Nichols. It was later passed on to
https://github.com/jgritman/httpbuilder[Jason Gritman] who maintained it for several years.

The original intent of Http Builder NG was to fix a few bugs and add a slight enhancement to the original HTTPBuilder project. The slight enhancement was to make
HTTPBuilder conform to more modern Groovy DSL designs; however, it was not possible to update the original code to have a more modern typesafe DSL while preserving
backwards compatibility. I decided to just make a clean break and give the project a new name to make it clear that Http Builder NG is basically a complete re-write
and re-architecture.

== License

HTTP Builder NG is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2] open source license.

----
Copyright 2016 David Clark

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
----

== Architecture

FIXME: come up with overview and maybe some diagrams

== Configuration

The specific configuration options are discussed in the JavaDocs for the `https://dwclark.github.io/http-builder-ng/javadoc/groovyx/net/http/HttpBuilder.html[HttpBuilder]`,
`https://dwclark.github.io/http-builder-ng/javadoc/groovyx/net/http/HttpConfig.html[HttpConfig]` and
`https://dwclark.github.io/http-builder-ng/javadoc/groovyx/net/http/HttpObjectConfig.html[HttpObjectConfig]` interfaces.

=== Authentication

There are two methods of authentication supported: BASIC and DIGEST.

==== BASIC

https://en.wikipedia.org/wiki/Basic_access_authentication[BASIC Authentication] is supported via the `HttpConfig.Request.Auth` interface:

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.auth.basic 'admin', 'myp@$$w0rd'
}
----

There is nothing more to do on the client side.

==== DIGEST

https://en.wikipedia.org/wiki/Digest_access_authentication[DIGEST Authentication] is supported via the `HttpConfig.Request.Auth` interface:

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.auth.digest 'admin', 'myp@$$w0rd'
}
----

There is nothing more to do on the client side.

== Encoders

> TODO: document

== Parsers

> TODO: document

The resulting data from a request is based on the response content type. The default parsers are listed below:

* HTML - `org.jsoup.nodes.Document`
* JSON - Groovy JSON object (map)
* XML - `org.w3c.dom.Document`
* TEXT - String of text

However, they may be overridden at configuration-time.

== Client Library Integration

> TODO: document

== Examples

This section contains some stand-alone examples of how you can use `HttpBuilder`. There are unit test versions for most of these examples. See the
`ExamplesSpec.groovy` file for more details.

=== Resource Last Modified (HEAD)

Suppose you want to see when the last time a jar in the public Maven repository was updated. Assuming the server is exposing the correct date, you can
use the `Last-Modified` header for the resource to figure out the date. A `HEAD` request works nicely for this, since you don't care about the actual
file content at this time, you just want the header information. `HttpBuilder` makes this easy:

[source,groovy]
----
String uri = 'http://central.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.7/groovy-all-2.4.7.jar'
Date lastModified = configure {
    request.uri = uri
}.head(Date) {
    response.success { FromServer resp ->
        String value = FromServer.Header.find(
            resp.headers,
            'Last-Modified'
        )?.value
        value ? Date.parse(
            'EEE, dd MMM yyyy  H:mm:ss zzz',
            value
        ) : null
    }
}

println "Groovy 2.4.7 last modified ${lastModified.format('MM/dd/yyyy HH:mm')}"
----

In the example we use the URL for the Groovy 2.4.7 jar file from the Maven Central Repository and execute a `HEAD` request on it and extract the
`Last-Modified` header and convert it to a `java.util.Date` object and return it as the result. We end up with a resulting output line something like:

    Groovy 2.4.7 last modified 06/07/2016 03:38

=== Scraping Web Content (GET)

Scraping content from web sites doesn't seem to be a prevalent as it was years ago, but it's a lot easier than it used to be. By default, `text/html`
content is parsed with the https://jsoup.org/[JSoup] HTML parser into a `Document` object:

[source,groovy]
----
Document page = configure {
    request.uri = 'https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all'
}.get()

String license = page.select('span.b.lic').collect { it.text() }.join(', ')

then:
println "Groovy is licensed under: ${license}"
----

In the example we make a `GET` request to the a secondary Maven repository to fetch the main entry page for the `groovy-all` artifact, which has the
license information on it. The page is returned and parsed into a JSoup `Document` which we can then run a CSS selection query on to extract the
license information and display it. You will end up with:

    Groovy is licensed under: Apache 2.0


