= Http Builder NG Users Guide
David Clark & Christopher J. Stehno
v0.9.16, September 2016
:toc: left
:toclevels: 3

== Introduction

WARNING: This document is a work-in-progress, and currently has a lot of gaps. We are working to fill in the holes, but feel free to suggest content by creating an issue.

Http Builder NG is a modern Groovy DSL for making http requests. It requires Java 8 and a modern Groovy. It is built against Groovy 2.4.x,
but it doesn't make any assumptions about which version of Groovy you are using. The main goal of Http Builder NG is to allow you to make
http requests in a natural and readable way.

The project web site is: https://github.com/dwclark/http-builder-ng

Issue tracking is handled via GitHub: https://github.com/dwclark/http-builder-ng/issues

== History

Http Builder NG was forked from the HTTPBuilder project originally developed by Thomas Nichols. It was later passed on to
https://github.com/jgritman/httpbuilder[Jason Gritman] who maintained it for several years.

The original intent of Http Builder NG was to fix a few bugs and add a slight enhancement to the original HTTPBuilder project. The slight enhancement was to make
HTTPBuilder conform to more modern Groovy DSL designs; however, it was not possible to update the original code to have a more modern typesafe DSL while preserving
backwards compatibility. I decided to just make a clean break and give the project a new name to make it clear that Http Builder NG is basically a complete re-write
and re-architecture.

== License

HTTP Builder NG is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2] open source license.

----
Copyright 2016 David Clark

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
----

== Architecture

FIXME: come up with overview and maybe some diagrams

== Configuration

The specific configuration options are discussed in the JavaDocs for the `https://dwclark.github.io/http-builder-ng/javadoc/groovyx/net/http/HttpBuilder.html[HttpBuilder]`,
`https://dwclark.github.io/http-builder-ng/javadoc/groovyx/net/http/HttpConfig.html[HttpConfig]` and
`https://dwclark.github.io/http-builder-ng/javadoc/groovyx/net/http/HttpObjectConfig.html[HttpObjectConfig]` interfaces.

=== Authentication

There are two methods of authentication supported: BASIC and DIGEST.

==== BASIC

https://en.wikipedia.org/wiki/Basic_access_authentication[BASIC Authentication] is supported via the `HttpConfig.Request.Auth` interface:

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.auth.basic 'admin', 'myp@$$w0rd'
}
----

There is nothing more to do on the client side.

==== DIGEST

https://en.wikipedia.org/wiki/Digest_access_authentication[DIGEST Authentication] is supported via the `HttpConfig.Request.Auth` interface:

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.auth.digest 'admin', 'myp@$$w0rd'
}
----

There is nothing more to do on the client side.

== Encoders

Content encoders are used to convert request body content to a different format before handing off to the underlying HTTP client. An encoder is implemented as a
`java.util.function.BiConsumer<ChainedHttpConfig,ToServer>` function where the provided implementation of the `ToServer` provides the data. See the `toServer(InputStream)`
method.

Encoders are provided in the request configuration (`HttpConfig.Request.encoder(String,BiConsumer<ChainedHttpConfig,ToServer>)`) mapped to a content type that they should be
used to handle. Say we wanted to be able to send `Date` objects to the server in a specific format as the request body:

[source,groovy]
----
HttpBuilder.configure {
    request.uri = 'http://locahost:1234/schedule'
    request.body = new Date()
    request.contentType = 'text/date-time'
    request.encoder('text/date-time'){ ChainedHttpConfig config, ToServer req->
        req.toServer(new ByteArrayInputStream("DATE-TIME: ${config.request.body.format('yyyyMMdd.HHmm')}".bytes))
    }
}.post()
----

Notice that a Groovy `Closure` is usable as a `BiConsumer` function. The `Date` object in the request is formatted as String, converted to bytes and pushed to the request
`InputStream`.

Default encoders are provided for: CSV, JSON and TEXT content.

== Parsers

The response body content resulting form a request is parsed based on the response content type. Content parsers may be configured using the
`HttpConfig.Response.parser(String, BiFunction<ChainedHttpConfig, FromServer, Object>)` method, which takes a `BiFunction` and the response content type it is mapped to. The function (or Closure)
accepts a `ChainedHttpConfig` object, and a `FromServer` instance and returns the parsed `Object`. If we had a server providing the current time as a response like `DATE-TIME: MM/dd/yyyy HH:mm:ss`
we could request the time with the following code:

[source,groovy]
----
Date date = HttpBuilder.configure {
    request.uri = 'http://localhost:1234/currenttime'
}.get(Date){
    response.parser('text/date-time'){ ChainedHttpConfig cfg, FromServer fs, Object obj->
        Date.parse('MM/dd/yyyy HH:mm:ss', fs.inputStream.text)
    }
}
----

which would parse the incoming response and convert it to a `Date` object.

Default parsers are provided for: HTML (`org.jsoup.nodes.Document`), JSON (Groovy JSON map), XML (`org.w3c.dom.Document`) and TEXT (String).

== Interceptors

The `HttpObjectConfig` (used in the `configure()` method, allows the configuration of global request/response
interceptors, which can perform operations before and after every request/response on the client. For example,
if you wanted to make a POST request and return only the time elapsed during the request/response handling, you
could do something like the following:

[source,groovy]
----
long elapsed = configure {
    request.uri = 'https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all'
    execution.interceptor(GET) { cfg, fx ->
        long started = System.currentTimeMillis()
        fx.apply(cfg)
        System.currentTimeMillis() - started
    }
}.get(Long, NO_OP)

println "Elapsed time for request: $elapsed ms"
----

This interceptor on the GET requests will calculate the time spent in the actual request handling (the
call to `fx.apply(cfg)` and return the elapsed time as the result of the request (ignoring the actual
response content from the server). The displayed result will be something like:

    Elapsed time for request: 865 ms

Using interceptors you can also modify the data before and after the `apply()` method is called.

== Client Library Integration

By default, the HTTP Builder NG library has two HTTP client implementations, one based on the Apache Http Components and the other based on `HttpUrlConnection`; however, there is
no reason other HTTP clients could not be used, perhaps the https://github.com/google/google-http-java-client[Google HTTP Java Client] if needed.

A client implementation is an extension of the abstract `HttpBuilder` class, which must implement a handful of abstract methods for the handling the HTTP verbs:

[source,groovy]
----
protected abstract Object doGet(final ChainedHttpConfig config);
protected abstract Object doHead(final ChainedHttpConfig config);
protected abstract Object doPost(final ChainedHttpConfig config);
protected abstract Object doPut(final ChainedHttpConfig config);
protected abstract Object doDelete(final ChainedHttpConfig config);
----

There is also an abstract method for retrieving the client configuration, though generally this will be a simple getter:

[source,groovy]
----
protected abstract ChainedHttpConfig getObjectConfig();
----

And finally a method to retrieve the threading interface, again this is generally a getter for the configured thread executor.

[source,groovy]
----
public abstract Executor getExecutor();
----

Once the abstract contract is satisfied, you can use the new client just as the others, with your client in the factory function:

[source,groovy]
----
HttpBuilder.configure({ c -> new GoogleHttpBuilder(c); } as Function){
    request.uri = 'http://localhost:10101/foo'
}
----

If you come up with something generally useful, feel free to create a pull request and we may be able to bring it into the project.

== Examples

This section contains some stand-alone examples of how you can use `HttpBuilder`. There are unit test versions for most of these examples. See the
`ExamplesSpec.groovy` file for more details.

=== Resource Last Modified (HEAD)

Suppose you want to see when the last time a jar in the public Maven repository was updated. Assuming the server is exposing the correct date, you can
use the `Last-Modified` header for the resource to figure out the date. A `HEAD` request works nicely for this, since you don't care about the actual
file content at this time, you just want the header information. `HttpBuilder` makes this easy:

[source,groovy]
----
String uri = 'http://central.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.7/groovy-all-2.4.7.jar'
Date lastModified = configure {
    request.uri = uri
}.head(Date) {
    response.success { FromServer resp ->
        String value = FromServer.Header.find(
            resp.headers,
            'Last-Modified'
        )?.value
        value ? Date.parse(
            'EEE, dd MMM yyyy  H:mm:ss zzz',
            value
        ) : null
    }
}

println "Groovy 2.4.7 last modified ${lastModified.format('MM/dd/yyyy HH:mm')}"
----

In the example we use the URL for the Groovy 2.4.7 jar file from the Maven Central Repository and execute a `HEAD` request on it and extract the
`Last-Modified` header and convert it to a `java.util.Date` object and return it as the result. We end up with a resulting output line something like:

    Groovy 2.4.7 last modified 06/07/2016 03:38

=== Scraping Web Content (GET)

Scraping content from web sites doesn't seem to be a prevalent as it was years ago, but it's a lot easier than it used to be. By default, `text/html`
content is parsed with the https://jsoup.org/[JSoup] HTML parser into a `Document` object:

[source,groovy]
----
Document page = configure {
    request.uri = 'https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all'
}.get()

String license = page.select('span.b.lic').collect { it.text() }.join(', ')

println "Groovy is licensed under: ${license}"
----

In the example we make a `GET` request to the a secondary Maven repository to fetch the main entry page for the `groovy-all` artifact, which has the
license information on it. The page is returned and parsed into a JSoup `Document` which we can then run a CSS selection query on to extract the
license information and display it. You will end up with:

    Groovy is licensed under: Apache 2.0

=== Sending/Receiving JSON Data (POST)

Posting JSON content to the server and parsing the response body to build an object from it is pretty common in RESTful interfaces. You can do this by creating
a POST request with a "Content-Type" of `application/json` and a custom response parser:

[source,groovy]
----
ItemScore itemScore = configure {
    request.uri = 'http://httpbin.org'
    request.contentType = JSON[0]
    response.parser(JSON[0]) { config, resp ->
        new ItemScore(NativeHandlers.Parsers.json(config, resp).json)
    }
}.post(ItemScore) {
    request.uri.path = '/post'
    request.body = new ItemScore('ASDFASEACV235', 90786)
}

println "Your score for item (${itemScore.item}) was (${itemScore.score})."
----

The custom response parser is needed to convert the parsed JSON data into your expected response data object. By default, the `application/json` response
content type will be parsed to a JSON object (lazy map); however, in this case we want the response to be an instance of the `ItemScore` class. The example
simply posts an `ItemScore` object (as a JSON string) to the server, which responds with the JSON string that it was provided.

The additional `.json` property call on the parsed data is to extract the JSON data from the response envelope - the site provides other useful information about
the request. The end result is the following display:

    Your score for item (ASDFASEACV235) was (90786).
