= Http Builder NG Users Guide
David Clark & Christopher J. Stehno
v0.9.12, August 2016
:toc: left
:toclevels: 3

== Introduction

WARNING: This document is a work-in-progress, and currently has a lot of gaps. We are working to fill in the holes, but feel free to suggest content by creating an issue.

Http Builder NG is a modern Groovy DSL for making http requests. It requires Java 8 and a modern Groovy. It is built against Groovy 2.4.x,
but it doesn't make any assumptions about which version of Groovy you are using. The main goal of Http Builder NG is to allow you to make
http requests in a natural and readable way.

The project web site is: https://github.com/dwclark/http-builder-ng

Issue tracking is handled via GitHub: https://github.com/dwclark/http-builder-ng/issues

== History

Http Builder NG was forked from the HTTPBuilder project originally developed by Thomas Nichols. It was later passed on to
https://github.com/jgritman/httpbuilder[Jason Gritman] who maintained it for several years.

The original intent of Http Builder NG was to fix a few bugs and add a slight enhancement to the original HTTPBuilder project. The slight enhancement was to make
HTTPBuilder conform to more modern Groovy DSL designs; however, it was not possible to update the original code to have a more modern typesafe DSL while preserving
backwards compatibility. I decided to just make a clean break and give the project a new name to make it clear that Http Builder NG is basically a complete re-write
and re-architecture.

== License

HTTP Builder NG is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2] open source license.

----
Copyright 2016 David Clark

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
----

== Architecture

> TBD: come up with overview and maybe some diagrams

== Common Configuration

The `HttpBuilder` is configured using one of the three static `configure` methods:

[source,groovy]
----
HttpBuilder configure(Function<HttpObjectConfig, ? extends HttpBuilder> factory)

HttpBuilder configure(@DelegatesTo(HttpObjectConfig) Closure closure)

HttpBuilder configure(Function<HttpObjectConfig, ? extends HttpBuilder> factory, @DelegatesTo(HttpObjectConfig) Closure closure)
----

Where the `factory` parameter is a `Function` used to instantiate the underlying builder with the appropriate HTTP Client implementation. Two implementations are provided by default, one based on the
Apache HTTPClient, and the other based on the `HttpURLConnection` class. It is generally preferable to use the Apache implementation for most use cases; however, the `HttpURLConnection` is instantiated
by default. Both are fully supported.

The `closure` parameter is used to provide configuration for the client instance. Configuration at this level will be applied to all verbs executed on the client. There are two configuration interfaces
available _only_ at the global configuration level: `Execution` and `Client`. The rest of the configuration interfaces are available at the global and per-verb levels.

=== `Execution` Configuration

The `Execution` configuration interface provides a means of configuring the execution-specific properties of the underlying HTTP client.

> TBD: more details, relations of thread/executor, ssl context, and interceptors

=== `Client` Configuration

The `Client` configuration interface allows configuration of client-centric properties. Currently, the only supported property is the supported HTTP Cookie version used by the underlying clients. The
`HttpBuilder` implementations will support Cookies at version `0` by default, which is what the Java Servlet API accepts. This can be modified, but care must be taken to ensure that your server
supports and accepts the configured Cookie version.

=== `Request` Configuration

The `Request` configuration interface provides configuration options available on the outgoing HTTP request.

==== `uri`

The `request.uri` is the URI of the HTTP endpoint for the request. It may be specified as a `URI`, a `String` or modified as a `UriBuilder`. The `uri` may be configured in the global configuration as
a base URL and then appended in the per-verb configuration, as follows:

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
}

http.get {
    request.uri.path = '/foo'
}

http.post {
    request.uri.path = '/bar'
}
----

Which allows multiple verb requests to be configured against the same `HttpBuilder`. See the `UriBuilder` documentation for more details.

The `uri` is the only required configuration property.

==== `contentType`

The `contentType` property is used to specify the `Content-Type` header value for the request.

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.contentType 'text/json'
}

http.post {
    request.uri.path = '/bar'
    request.contentType 'text/csv'
}
----

By default, the value will be `text/plain`.

==== `charset`

The `charset` property is used to specify the character set used by the request.

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.charset 'utf-16'
}

http.post {
    request.uri.path = '/bar'
    request.charset 'utf-8'
}
----

It is often advisable to specify the `charset`, when `contentType` is specified. By default, the value will be `utf-8`.

==== `headers`

The `headers` property allows the direct specification of the request headers as a `Map<String,String>`. Be aware that `Content-Type` is technically a header value and it is up to the implementation
to determine which configuration will win out if both are configured.

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.headers([ ClientId: '987sdfsdf9uh' ])
}

http.post {
    request.uri.path = '/bar'
    request.headers([ AccessCode: '99887766' ])
}
----

==== `accept`

The `accept` property allows configuration of the request `Accept` header, which may be used to specify certain media types which are acceptable for the response.

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.accept 'image/jpeg'
}

http.post {
    request.uri.path = '/bar'
    request.accept 'image/tiff', 'image/png'
}
----

==== `cookie`

The `cookie` configuration options provide a means of adding HTTP Cookies to the request. Cookies are defined with a `name`, `value`, and optional `expires` Date.

[source,groovy]
----
def http = HttpBuilder.configure {
    request.uri = 'http://localhost:10101'
    request.cookie 'seen-before', 'true'
}

http.post {
    request.uri.path = '/bar'
    request.cookie 'last-page', 'item-list', Date.parse('MM/dd/yyyy', '12/31/2016')
}
----

WARNING: Cookies are additive, once a Cookie is defined (e.g. in the global configuration), you cannot overwrite it in per-verb configurations.

As noted in the `Client` configuration above, the default Cookie version supported is `0`, but this may be modified.

==== `body`

==== `encoder`

==== `auth`

        Basic
        Digest

=== `Response` Configuration

    when
    parser
    success/failure


HTTPS/SSL

notes about support and configuration...


[source,groovy]
----
int maxThreads = 2

def google = HttpBuilder.configure(apacheBuilder) {
    request.uri = 'http://www.google.com'
    execution.maxThreads = maxThreads
    execution.executor =  Executors.newFixedThreadPool(maxThreads)
}
----

> The verb sections should be interesting examples for each of the verbs most common use cases

== Verbs

include::verbs/get.adoc[]
include::verbs/post.adoc[]

=== PUT

> TBD...

=== HEAD

> TBD...

=== DELETE

> TBD...

=== TRACE

> TBD...

=== OPTIONS

> TBD...

== Encoders & Parsers

> TBD...

== Client Library Integration

> TBD...