= Http Builder NG Users Guide
David Clark & Christopher J. Stehno
v0.9.12, August 2016
:toc: left
:toclevels: 3

== Introduction

WARNING: This document is a work-in-progress, and currently has a lot of gaps. We are working to fill in the holes, but feel free to suggest content by creating an issue.

Http Builder NG is a modern Groovy DSL for making http requests. It requires Java 8 and a modern Groovy. It is built against Groovy 2.4.x,
but it doesn't make any assumptions about which version of Groovy you are using. The main goal of Http Builder NG is to allow you to make
http requests in a natural and readable way.

The project web site is: https://github.com/dwclark/http-builder-ng

Issue tracking is handled via GitHub: https://github.com/dwclark/http-builder-ng/issues

== History

Http Builder NG was forked from the HTTPBuilder project originally developed by Thomas Nichols. It was later passed on to
https://github.com/jgritman/httpbuilder[Jason Gritman] who maintained it for several years.

The original intent of Http Builder NG was to fix a few bugs and add a slight enhancement to the original HTTPBuilder project. The slight enhancement was to make
HTTPBuilder conform to more modern Groovy DSL designs; however, it was not possible to update the original code to have a more modern typesafe DSL while preserving
backwards compatibility. I decided to just make a clean break and give the project a new name to make it clear that Http Builder NG is basically a complete re-write
and re-architecture.

== License

HTTP Builder NG is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2] open source license.

----
Copyright 2016 David Clark

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
----

== Architecture

> TBD...

== Common Configuration

> TBD: document full scope of `configure` options...

[source,groovy]
----
int maxThreads = 2

def google = HttpBuilder.configure(apacheBuilder) {
    request.uri = 'http://www.google.com'
    execution.maxThreads = maxThreads
    execution.executor =  Executors.newFixedThreadPool(maxThreads)
}
----

== Verbs

include::verbs/get.adoc[]
include::verbs/post.adoc[]

=== PUT

> TBD...

=== HEAD

> TBD...

=== DELETE

> TBD...

=== TRACE

> TBD...

=== OPTIONS

> TBD...

== Encoders & Parsers

> TBD...

== Client Library Integration

> TBD...