
== Request


=== Multipart

HttpBuilder-NG supports multipart request content such as file uploads, with either the generic `MultipartEncoder` or one of the client-specific
encoders. For example, the `OkHttpBuilder` may use the `OkHttpEncoders.&multipart` encoder:

[source,groovy]
----
import groovyx.net.http.OkHttpBuilder
import groovyx.net.http.*

File someFile = // ...

OkHttpBuilder.configure {
    request.uri = 'http://example.com'
}.post {
    request.uri.path = '/upload'
    request.contentType = 'multipart/form-data'
    request.body = multipart {
        field 'name', 'This is my file'
        part 'file', 'myfile.txt', 'text/plain', someFile
    }
    request.encoder 'multipart/form-data', OkHttpEncoders.&multipart
}
----

which would `POST` the content of the file, `someFile` along with the specified `name` field to the server as a `multipart/form-data` request. The
important parts of the example are the `multipart` DSL extension, which is provided by the `MultipartContent` class and aids in creating the upload
content in the correct format. The multipart encoder is used to convert the request content into the multipart message format expected by a server.
Notice that the encoder is specific to the `OkHttpBuilder`, which we are using in this case.

The available multipart encoders:

* `groovyx.net.http.CoreEncoders::multipart` - a generic minimalistic multipart encoder for use with the core Java client or any of the others (requires the JavaMail API).
* `groovyx.net.http.OkHttpEncoders::multipart` - the encoder using OkHttp-specific multipart encoding.
* `groovyx.net.http.ApacheEncoders::multipart` - the encoder using Apache client specific multipart encoding.

The encoding of the parts is done using the encoders configured on the `HttpBuilder` executing the request. Any encoders required to encode the parts
of a multipart content object must be specified beforehand.
