== Troubleshooting

This section will discuss any recurring issues with simple non-code solutions.

=== 'typecheckhttpconfig.groovy' was not found

NOTE: As of v0.18.0 the `typecheckedhttpconfig.groovy` file has been removed, so this should not be an issue going forward.

We have had a few issues reported related to the following error (https://github.com/http-builder-ng/http-builder-ng/issues/107[#107],
https://github.com/http-builder-ng/http-builder-ng/issues/115[#115], https://github.com/http-builder-ng/http-builder-ng/issues/144[#144]):

```
Static type checking extension 'typecheckhttpconfig.groovy' was not found on the class path.
```

This seems to be related to the version of Tomcat being used (by itself, or embedded in Grails or Spring-Boot). You will get this error on Tomcat
version 7.x (and possibly older versions), though Tomcat 8.x does not have this issue.

In all three cases, the solution was just to upgrade the version of Tomcat being used; however, if this is _not_ an acceptable solution in your case,
you can extract the `typecheckhttpconfig.groovy` and `59f7b2e5d5a78b25c6b21eb3b6b4f9ff77d11671.groovy` files from the `http-builder-ng-core` jar and
add them to the application's war root classpath.

If neither of these solve the problem for you, please feel free to create an issue, but please provide a working example that we can test against.

=== Encoded URI Path

In some cases HTTP server endpoints will have encoded portions of the path so that you end up with a URI such as:

    http://localhost:1234/api/v4/projects/myteam%2Fmyrepo/repository/files/myfile.json

Notice the `myteam%2Fmyrepo` is a URI-encoded string. Using the standard `request.uri` approach with this URI will fail since the encoding will be decoded when used to create the URI. We have provided
and alternate approach to solve this problem (see <<_uri>> Configuration section). Using the `request.raw` configuration option, you can specify a "raw" URI string which will preserve any
encoding. In fact, it will perform _no_ encoding or decoding of path or query string elements, so it all must be done in your provided URI string.

An example of this approach would be:

[source,groovy]
----
def result = JavaHttpBuilder.configure {
    request.raw = "http://localhost:1234/api/v4/projects/myteam%2Fmyrepo/repository/files/myfile.json"
}.get()
----

which would properly preserve the encoded URI content.
